### ISSUE TITLE
usb-tablet does not work as described with 10.9.2

### ISSUE THREAD

**Issue by milosivanovic** [pmj/QemuUSBTablet-OSX#2]
# Description

Since I did not test what usb-tablet looked like _without_ your driver installed, I can't tell whether this is default behaviour or if it's enhanced by the driver. The pointer is always accurate right in the centre of the screen, but as you come closer to each corner the OS X pointer is always ahead (closer to the corner than the VNC mouse).
# Steps to reproduce:
1. Install OS X 10.9.2 with usb-kbd and usb-mouse
2. Install usb-tablet driver at first convenience
3. Shut down VM
4. Replace usb-mouse with usb-tablet in QEMU configuration
5. Boot VM
# Steps to resolve:
1. Upgrade to 10.9.5 (10.9.3 and 10.9.4 untested).

You do not have to spend time resolving this issue; rather, it would be good to specify that 10.9.2 does not work on your website (if the issue can be 100% confirmed.)

**Comment by pmj** [comment]
Hmm! That's pretty odd, since commit 29ab5e9 that behaviour has been disabled for the 10.9+ version of the driver, and since f8a256c also for 10.8.x and earlier. (both of those commits are part of the 1.1 release)

I'd need to do a deep dive on this to work out what's going on, although I suppose it might be sufficient to compare Apple's HID source code releases for various 10.9.x versions. As you say, not terribly high priority as it behaves correctly in 10.9.5 which is what most 10.9 users are going to be running. I don't know when I'll next have time to look into this, but thanks for reporting it anyway, it will eventually get fixed if at all possible!

**Comment by pmj** [comment]
I've just published our 1.2 update to the driver, and I tested it with 10.9.5. The update fixed it for 10.10, and it seems for 10.9.5 as well. Sorry for the huge delay - please give the new version a go - download binaries here: http://philjordan.eu/osx-virt/
