### ISSUE TITLE
usb-tablet driver 1.1 does not work with 10.11 EL Capitan

### ISSUE THREAD

**Issue by swordqiu** [pmj/QemuUSBTablet-OSX#3]
We'd high appreciate if you could have time to make it work with 10.11 EL Capitan. Many thanks! Great job anyway.

**Comment by pmj** [comment]
Hi - I am aware of the issue, it also doesn't work with later revisions of Yosemite (10.10.5). I have not had free time to solve this, and I'm not sure when I will have the time. If you need this fixed for a commercial project please contact me by email and we can work something out.

**Comment by 128keaton** [comment]
I am having the same issues too. If you need help, let me know

**Comment by pmj** [comment]
Just an update: a solution to the 10.11 problem is coming soon. Not sure about the 10.10 issue yet.

**Comment by pmj** [comment]
Hi all,

Thanks for your patience with this. I've just published a new version of the driver, 1.2, which works on 10.10 through 10.12. Please get it here: http://philjordan.eu/osx-virt/ and let me know if it works for you. Thanks!

**Comment by osxhiduser** [comment]
Great work! Could you share your latest source code changes for Version 1.2? This would be highly appreciated!
Maybe this is not the right place, but how did you find out that you needed to reset the protocol field in the HID Report, for example, for the driver to handle the absolute mouse positions correctly?

**Comment by pmj** [comment]
The code is already up to date on github. The main code changes are in commit c9b0ddd - the remaining commits deal with multiple OSX/macOS version compatibility and related installer issues. The fix is essentially the same as for Yosemite, but 10.11 and newer have a new USB stack, and so the USB HID driver didn't match up anymore.

Regarding how we figured out how to fix it originally: This was mainly a case of inspecting the IOHIDFamily/IOUSBHIDDriver source code from Apple, and also comparing Qemu's tablet HID report descriptor with VMWare's - the latter works without any special driver, after all. I'm actually working on a patch against Qemu for adding a tablet device which works out of the box with OSX/macOS guests. I'm planning to submit that to the mailing list next week; with a bit of luck, you won't need this driver anymore as of Qemu 2.9.
